{
  try {
    for (    X509Certificate cert : this.certificates) {
      getChecker().check(cert);
    }
    if (this.expected != null) {
      Assert.fail("Expected exception of type " + this.expected.getClass());
    }
  }
 catch (  final GeneralSecurityException e) {
    if (this.expected == null) {
      Assert.fail("Revocation check failed unexpectedly with exception: " + e);
    }
 else {
      final Class<?> expectedClass=this.expected.getClass();
      final Class<?> actualClass=e.getClass();
      Assert.assertTrue(String.format("Expected exception of type %s but got %s",expectedClass,actualClass),expectedClass.isAssignableFrom(actualClass));
    }
  }
}
